# 数据操作



Debug的时候查看数据/权重的维度等

In [ ]:
import torch
x = torch.arange(12).reshape(3,4) #生成0-11的torch数据
type(x) #输出数据的类型
x.shape #输出变量尺寸
x.shape[0] #指定维度的尺寸
len(x) #只会输出第一维的长度
x.numel() #输出所有的元素总数
X = x.reshape(3, 4) #修改变量形状，但是实际使用一般只会调换维度，用不到这个

3 12


使用全0、全1、其他常量，或者从特定分布中随机采样的数字    
一般自己生成一些初始化权重/输入数据测试的时候用用

In [2]:
import torch
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))
torch.randn(3, 4)
x = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.exp(x) #批量进行幂运算

tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

把多个张量*连结*（concatenate）在一起，注意dim的维度    
数据拼接的时候用得到

In [3]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X,Y)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

一般在计算模型准确率时会用到

In [4]:
X == Y #比较两个tensor中变量的一致性
X.sum() #两个tensor中所有元素求和，得到一个单元素张量，可以进一步变成标量

tensor(66.)

可以用`[-1]`选择最后一个元素，可以用`[1:3]`选择第二个和第三个元素(左闭右开)   
tensor的数据选择/过滤是最麻烦的，尤其是[:,-1]这种，维度会减少，需要多实践

In [5]:
X[-1], X[1:3]

# 将大小为1的张量转换为Python标量
a = torch.tensor([3.5]) 
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)