# 基于pytorch的线性代数运算表达

In [5]:
import torch
A = torch.arange(20).reshape(5, 2, 2)
A.T #矩阵转置
B = A.clone() #通过分配内存，将A的一个副本分配给B


两个矩阵的按元素乘法称为*Hadamard积*（Hadamard product）（数学符号$\odot$）

In [11]:
A * B

tensor([[[  0,   1],
         [  4,   9]],

        [[ 16,  25],
         [ 36,  49]],

        [[ 64,  81],
         [100, 121]],

        [[144, 169],
         [196, 225]],

        [[256, 289],
         [324, 361]]])

In [13]:
A

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]]])

In [ ]:
# 指定张量沿哪一个轴来通过求和降低维度
A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)
A.sum(axis=[0, 1])
A.sum()

A = A.float() #计算均值时要先修改数据类型从tensor.long变为float
# 求均值
A.mean()
A.mean(axis=0)
sum_A = A.sum(axis=1, keepdims=True) #计算总和或均值时保持轴数不变

# 某个轴计算`A`元素的累积总和，注意是累积总和，基本上没什么用
A.cumsum(axis=0)

x = torch.rand(4)
y = torch.ones(4)
# 点积是相同位置的按元素乘积的和，输入必须是一维张量
torch.dot(x, y)

# 矩阵相乘运算，最最重要的；注意矩阵形状
x = x.reshape(2,2)
y = y.reshape(2,2)
x @ y # 等价于torch.mm(x,y)

tensor([[0.6992, 0.6992],
        [0.9081, 0.9081]])

$L_2$*范数*是向量元素平方和的平方根：
$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$$

In [146]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$范数，它表示为向量元素的绝对值之和：
$$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|$$

In [147]:
torch.abs(u).sum()

tensor(7.)

矩阵
的*Frobenius范数*（Frobenius norm）是矩阵元素平方和的平方根：
$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$$

In [148]:
torch.norm(torch.ones((4, 9)))

tensor(6.)